arch: "NAR"

exp_name: "test"

seed: 20211117

is_cuda: True

space: "nasbench"
train_size: 34362
val_size: 8000
drop_last: True
data_loader_workers: 6

batch_size: 256

start_epochs: 0
ranker_epochs: 24

ranker:
  n_tier: 5
  n_arch_patch: 19
  d_patch: 7
  d_patch_vec: 512
  d_model: 512
  d_ffn_inner: 2048
  d_tier_prj_inner: 4096
  n_layers: 6
  n_head: 8
  d_k: 64
  d_v: 64
  dropout: 0.1
  n_position: 200
  scale_prj: True

optimizer:
  betas: (0.9, 0.98)
  eps: 1e-09
  weight_decay: 5e-4

lr_scheduler:
  lr_mul: 0.5
  n_warmup_steps: 4000
